### ISSUE TITLE
NPE Spectral libraries to feature lists 

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine#1548]
MZType is maybe not set for the feature - and row. Maybe as we use precursor mz?
Or maybe MS1 spectra just dont have one which makes sense? but we might want to use the base peak in the MS1 spectrum then?

```
2023-12-04 13:17:04 INFO   io.github.mzmine.main.MZmineCore setupAndRunModule Setting parameters for module MS/MS spectral networking (Molecular networking)
2023-12-04 13:17:17 FINEST io.github.mzmine.main.MZmineCore setupAndRunModule Starting module MS/MS spectral networking (Molecular networking) with parameters Feature lists: Merged feature list, m/z tolerance (MS2): 0.003 m/z or 10.0 ppm, Only best MS2 scan: true, Max precursor m/z delta: true, Minimum matched signals: 4, Min cosine similarity: 0.6, Check MS2 neutral loss similarity: true, Signal filters: Remove residual precursor m/z: true, Crop to top N signals: 250, Signal threshold (intensity filter): 50, Intensity filter at >N signals: 0.98
2023-12-04 13:17:17 FINEST io.github.mzmine.main.MZmineCore runMZmineModule Module MS/MS spectral networking (Molecular networking) called at 2023-12-04T12:17:17.902729700Z
2023-12-04 13:17:17 FINEST io.github.mzmine.taskcontrol.impl.TaskQueue addWrappedTask Adding task "Check similarity of MSMS scans (mass lists)" to the task controller queue
2023-12-04 13:17:17 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Starting processing of task Check similarity of MSMS scans (mass lists)
2023-12-04 13:17:17 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "io.github.mzmine.datamodel.features.FeatureListRow.getAverageMZ()" is null while processing task Check similarity of MSMS scans (mass lists)
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "io.github.mzmine.datamodel.features.FeatureListRow.getAverageMZ()" is null
	at io.github.mzmine.util.FeatureListRowSorter.getValue(FeatureListRowSorter.java:96)
	at io.github.mzmine.util.FeatureListRowSorter.compare(FeatureListRowSorter.java:58)
	at io.github.mzmine.util.FeatureListRowSorter.compare(FeatureListRowSorter.java:38)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:260)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.mergeSort(SortHelper.java:271)
	at com.sun.javafx.collections.SortHelper.sort(SortHelper.java:82)
	at com.sun.javafx.collections.SortHelper.sort(SortHelper.java:63)
	at com.sun.javafx.collections.ObservableListWrapper.sort(ObservableListWrapper.java:225)
	at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.prepareRowBestSpectrum(SpectralNetworkingTask.java:493)
	at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.checkRowsBestMs2(SpectralNetworkingTask.java:441)
	at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.run(SpectralNetworkingTask.java:364)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:64)

2023-12-04 13:17:17 FINEST io.github.mzmine.gui.MZmineGUI displayMessage Error - Unhandled exception in task Check similarity of MSMS scans (mass lists): java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "io.github.mzmine.datamodel.features.FeatureListRow.getAverageMZ()" is null (FeatureListRowSorter.java:96) - null
```

**Comment by SteffenHeu** [comment]
Also had this issue. should probably set precursor mz as mz during conversion

**Comment by robinschmid** [comment]
Done
