### ISSUE TITLE
Login in command line batch mode?

### ISSUE THREAD

**Issue by bsedio** [mzmine/mzmine#1827]
### Basic information

* My operating system and version: Texas Advanced Computing Center, Frontera supercomputer (Linux)
* My mzmine version: MZmine-4.0.8

### What happened

I ran MZmine-4.0.8 in batch mode on the Frontera supercomputer for the first time (using 'slurm'). I've attached the batch file and slurm file as text file (since GitHub won't allow me to upload .slurm or .mzbatch). Interestingly, it worked until it got to the Smoothing module, at which point I received the following error:

2024-05-02 18:15:46 INFO   io.github.mzmine.taskcontrol.impl.WrappedTask run Processing of task Detecting chromatograms in COFL2.mzXML done, status FINISHED
2024-05-02 18:15:46 INFO   io.github.mzmine.taskcontrol.impl.WrappedTask run Processing of task Chromatogram builder on 34 items done, status FINISHED
2024-05-02 18:15:46 INFO   io.github.mzmine.modules.batchmode.BatchTask processQueueStep Starting step # 5
2024-05-02 18:15:46 FINEST io.github.mzmine.modules.batchmode.BatchTask processQueueStep Module Smoothing called at 2024-05-02T23:15:46.639989637Z
2024-05-02 18:15:46 INFO   io.github.mzmine.gui.HeadLessDesktop displayMessage Requires user login. Open mzmine and login to a user
2024-05-02 18:15:46 INFO   io.github.mzmine.modules.batchmode.BatchTask processQueueStep Starting step # 6
2024-05-02 18:15:46 FINEST io.github.mzmine.modules.batchmode.BatchTask processQueueStep Module Local minimum feature resolver called at 2024-05-02T23:15:46.645838804Z
2024-05-02 18:15:46 INFO   io.github.mzmine.gui.HeadLessDesktop displayMessage Requires user login. Open mzmine and login to a user
2024-05-02 18:15:46 INFO   io.github.mzmine.modules.batchmode.BatchTask processQueueStep Starting step # 7
2024-05-02 18:15:46 FINEST io.github.mzmine.modules.batchmode.BatchTask processQueueStep Module 13C isotope filter (formerly: isotope grouper) called at 2024-05-02T23:15:46.652419181Z
2024-05-02 18:15:46 INFO   io.github.mzmine.gui.HeadLessDesktop displayMessage Requires user login. Open mzmine and login to a user
2024-05-02 18:15:46 INFO   io.github.mzmine.modules.batchmode.BatchTask processQueueStep Starting step # 8
2024-05-02 18:15:46 FINEST io.github.mzmine.modules.batchmode.BatchTask processQueueStep Module Isotopic peaks finder called at 2024-05-02T23:15:46.655666826Z
2024-05-02 18:15:46 INFO   io.github.mzmine.gui.HeadLessDesktop displayMessage Requires user login. Open mzmine and login to a user
2024-05-02 18:15:46 INFO   io.github.mzmine.modules.batchmode.BatchTask processQueueStep Starting step # 9
2024-05-02 18:15:46 FINEST io.github.mzmine.modules.batchmode.BatchTask processQueueStep Module Join aligner called at 2024-05-02T23:15:46.660198024Z
2024-05-02 18:15:46 INFO   io.github.mzmine.gui.HeadLessDesktop displayMessage Requires user login. Open mzmine and login to a user
2024-05-02 18:15:46 SEVERE io.github.mzmine.modules.batchmode.BatchModeModule runBatch Error while running batch. Cannot read the array length because "<local3>" is null
java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
	at io.github.mzmine.taskcontrol.utils.TaskUtils.waitForTasksToFinish(TaskUtils.java:75)
	at io.github.mzmine.modules.batchmode.BatchTask.runTasksIndividually(BatchTask.java:435)
	at io.github.mzmine.modules.batchmode.BatchTask.processQueueStep(BatchTask.java:390)
	at io.github.mzmine.modules.batchmode.BatchTask.run(BatchTask.java:226)
	at io.github.mzmine.modules.batchmode.BatchModeModule.runBatch(BatchModeModule.java:130)
	at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:246)

So it looks like MZmine is looking for a user login. Is it possible to log in before running MZmine in batch mode, either through a unix command that can be executed in the 'slurm' file that runs the job, or through the .mzbatch batch file?

Thank you for all of the incredible work you have done to improve MZmine!

Brian Sedio

[metabdemo_mzm4_mzbatch.txt](https://github.com/mzmine/mzmine3/files/15194944/metabdemo_mzm4_mzbatch.txt)
[metabdemo_mzm4_dev_slurm.txt](https://github.com/mzmine/mzmine3/files/15194945/metabdemo_mzm4_dev_slurm.txt)

**Comment by robinschmid** [comment]
It is possible to define the user in the config file but we will soon push a new release that takes a user file or credentials as input. 
Current option requires a user file in the user/.mzmine/users/YOURNAME.mzuser and then defining the user in the user/.mzmine/.mzconfig (or the config that you supply as command line argument).

Config defines user in preferences block:
```
<preferences>
    ....
    <parameter name="username">robinschmid</parameter> 
</preferences>
```
