### ISSUE TITLE
mzmine 4.1 does not read raw files on my macbook pro m1

### ISSUE THREAD

**Issue by wolski** [mzmine/mzmine#1942]
### Basic information

* My operating system and version: macOS 14.5 (23F79)
* My mzmine version: mzmine 4.1.0

### What happened

The problem seems to be related to the MZmine installation on my MacBook Pro laptop. 

I am running mzmine from the CMD. I am using an example, that runs on the laptop of my colleague. I did adjust all the paths to my settings. However, on my laptop, the example fails.

```
/Applications/MZmine.app/Contents/MacOS/MZmine \
  -user witold \
  -batch /Users/witoldwolski/Downloads/mzmine/20240618-cp.mzbatch \
  -temp /Users/witoldwolski/Downloads/mzmine/temp \
  -input "/Users/witoldwolski/Downloads/mzmine/tiny/*.raw" \
  -l /Users/witoldwolski/Dropbox/Computational_Metabolomics_Tests_Witold/MS2_libraries_MSP/GNPS-NIH-SMALLMOLECULEPHARMACOLOGICALLYACTIVE.msp \
  -o /Users/witoldwolski/Downloads/mzmine/output \
  1> error.1.log  \
  2> error.2.log

```

However, on my machine, mzmine does not produce any outputs.

I did look at the error logs, and it appears that mzmine fails to read the *raw files:

```
2024-07-01 11:12:55 INFO   io.github.mzmine.taskcontrol.impl.WrappedTask run Processing of task Opening file /Users/witoldwolski/Downloads/mzmine/tiny/POS_LimitFood_D00007_2_P_LF-001_V3_gr3_F.raw done, status PROCESSING
2024-07-01 11:12:56 WARNING io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask importStreamOrFile Error during mzML read: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
java.lang.RuntimeException: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
        at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.parseMzMlInternal(MSDKmzMLImportTask.java:581)
        at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.parseMzMl(MSDKmzMLImportTask.java:528)
        at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.importStreamOrFile(MSDKmzMLImportTask.java:185)
        at io.github.mzmine.modules.io.import_rawdata_thermo_raw.ThermoRawImportTask.run(ThermoRawImportTask.java:150)
        at io.github.mzmine.taskcontrol.impl.WrappedTask.run(WrappedTask.java:166)
        at io.github.mzmine.taskcontrol.threadpools.ThreadPoolTask.lambda$trackProgressTask$3(ThreadPoolTask.java:183)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
        at com.fasterxml.aalto.stax.StreamReaderImpl.throwWfe(StreamReaderImpl.java:1777)
        at com.fasterxml.aalto.stax.StreamReaderImpl.throwUnexpectedEOI(StreamReaderImpl.java:1796)
        at com.fasterxml.aalto.stax.StreamReaderImpl.handlePrologEoi(StreamReaderImpl.java:1756)
        at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:810)
        at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.parseMzMlInternal(MSDKmzMLImportTask.java:559)
        ... 10 more
```

Here is the error log.
[error.2.log](https://github.com/user-attachments/files/16050764/error.2.log)

I did websearch for the "java.lang.RuntimeException: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog" error but did not find anything which would help.

When running from the UI, the error looks like this:

<img width="1300" alt="image" src="https://github.com/mzmine/mzmine/assets/1926513/8f1308d5-659d-4b20-a1d7-e74072e30f42">

**Comment by ansgarkorf** [comment]
Hi,
can you open the raw files in mzmine at all? Can you test it with the UI on your macbook?

**Comment by wolski** [comment]
Sorry, but no, I Can't open a file through the UI either.

This is the log when going through the Menu:

```
Jul 01, 2024 1:47:44 PM io.github.mzmine.gui.mainwindow.MainMenuController runModule
INFO: Menu item activated for module io.github.mzmine.modules.io.import_rawdata_all.AllSpectralDataImportModule
Jul 01, 2024 1:47:44 PM io.github.mzmine.main.MZmineCore setupAndRunModule
INFO: Setting parameters for module Import MS data
Jul 01, 2024 1:47:53 PM io.github.mzmine.taskcontrol.impl.WrappedTask run
INFO: Starting processing of task Importing data
Jul 01, 2024 1:47:53 PM io.github.mzmine.taskcontrol.impl.WrappedTask run
INFO: Starting processing of task Opening file /Users/witoldwolski/Downloads/mzmine/tiny/POS_LimitFood_D00005_24_P_LF-016_V3_gr1_F.raw
Jul 01, 2024 1:47:53 PM io.github.mzmine.modules.io.import_rawdata_thermo_raw.ThermoRawImportTask run
INFO: Opening file /Users/witoldwolski/Downloads/mzmine/tiny/POS_LimitFood_D00005_24_P_LF-016_V3_gr1_F.raw
Jul 01, 2024 1:47:55 PM io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask importStreamOrFile
WARNING: Error during mzML read: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
java.lang.RuntimeException: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
        at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.parseMzMlInternal(MSDKmzMLImportTask.java:581)
        at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.parseMzMl(MSDKmzMLImportTask.java:528)
        at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.importStreamOrFile(MSDKmzMLImportTask.java:185)
        at io.github.mzmine.modules.io.import_rawdata_thermo_raw.ThermoRawImportTask.run(ThermoRawImportTask.java:150)
        at io.github.mzmine.taskcontrol.impl.WrappedTask.run(WrappedTask.java:166)
        at io.github.mzmine.taskcontrol.threadpools.ThreadPoolTask.lambda$trackProgressTask$3(ThreadPoolTask.java:183)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
        at com.fasterxml.aalto.stax.StreamReaderImpl.throwWfe(StreamReaderImpl.java:1777)
        at com.fasterxml.aalto.stax.StreamReaderImpl.throwUnexpectedEOI(StreamReaderImpl.java:1796)
        at com.fasterxml.aalto.stax.StreamReaderImpl.handlePrologEoi(StreamReaderImpl.java:1756)
        at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:810)
        at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.parseMzMlInternal(MSDKmzMLImportTask.java:559)
        ... 10 more

Jul 01, 2024 1:47:55 PM io.github.mzmine.taskcontrol.impl.WrappedTask run
INFO: Processing of task Opening file /Users/witoldwolski/Downloads/mzmine/tiny/POS_LimitFood_D00005_24_P_LF-016_V3_gr1_F.raw done, status PROCESSING
Jul 01, 2024 1:47:55 PM io.github.mzmine.taskcontrol.impl.WrappedTask run
INFO: Processing of task Importing data done, status FINISHED
```

**Comment by ansgarkorf** [comment]
Looks like the files are broken. Can you share an example file with us?

**Comment by leoschwarz** [comment]
I've edited the code in `ThermoRawImportTask.java` to invoke `mono ThermoRawFileParser.exe ...` instead of `ThermoRawFileParserMac ...` which made the problem disappear for me. In newer versions the `ThermoRawFileParserMac` seems to have been removed from `ThermaRawFileReader` (I've checked v1.4.4)

**Comment by tomas-pluskal** [comment]
`ThermoRawFileParserMac` is not a part of the standard ThermoRawFileParser download, it is a bundle package that includes ThermoRawFileParser and mono runtime. See the README in this folder: https://github.com/mzmine/mzmine/tree/master/mzmine-community/src/main/resources/vendorlib/thermo
The purpose of this is to make ThermoRawFileParser runnable on systems that do not have mono installed. Unfortunately, it seems it does not work 100%.

**Comment by leoschwarz** [comment]
My bad, thank you for pointing this out. So it seems the original version does run for me with Mono MDK installed but just the Mono runtime is not enough.

**Comment by SteffenHeu** [comment]
The Mac build environment on github was recently changed from an Intel-mac to the Apple silicon mac. Which means before, mzmine was emulated by rosetta and now it's running natively on apple silicon. Maybe this changes the way mono and the raw parser work together?

**Comment by briankleiboeker** [comment]
I am also having this problem, though from the GUI (v. 4.1.0) instead of CLI

Using the exampledata from [this issue](https://github.com/mzmine/mzmine/issues/1545), I'm able to import the the .mzML file just fine but when I import the .raw file it refuses to show up in the 'MS data files' tab of mzmine, though no error is ever displayed

I'm on an m1 macbook pro running macOS Sonoma 14.5

**Comment by SteffenHeu** [comment]
It seems that the bundled mono version is not working as expected. Can you try installing mono on your machine and try again?

**Comment by briankleiboeker** [comment]
Brilliant -- after encountering this problem, I installed mono in order to use ThermoRawFileParser to convert to mzML. Now that I have mono installed, I am able to import the .raw files perfectly. Thanks so much!
