### ISSUE TITLE
BatchModeModule runBatch Error while running batch. null

### ISSUE THREAD

**Issue by ashin947** [mzmine/mzmine#2026]
### Basic information

* My operating system and version: linux
* My mzmine version: mzmine4.2.0

### What happened

I downloaded mzmine_Linux_portable-4.2.0. zip and extracted it on a Linux server, but I encountered an error during batch processing. After reading the raw file, the following problem was displayed:
#***************************************************************
openjdk version "22.0.1" 2024-04-16
OpenJDK Runtime Environment Temurin-22.0.1+8 (build 22.0.1+8)
OpenJDK 64-Bit Server VM Temurin-22.0.1+8 (build 22.0.1+8, mixed mode)
2024-08-08 15:57:21 FINE   io.github.mzmine.main.MZmineCore init Initializing core classes..
2024-08-08 15:57:21 INFO   io.github.mzmine.main.MZmineCore main Starting mzmine 4.2.0
2024-08-08 15:57:21 FINEST io.github.mzmine.main.MZmineCore main mzmine arguments: -memory none -user ./ashin.mzuser -temp tmp -batch LINUX.mzbatch
2024-08-08 15:57:21 FINEST io.github.mzmine.main.MZmineCore main Java VM arguments: -Djpackage.app-version=4.2.0 -XX:MaxHeapFreeRatio=100 -XX:InitialRAMPercentage=30 -XX:MinRAMPercentage=80 -XX:MaxRAMPercentage=80 -enableassertions -Djava.util.logging.config.class=io.github.mzmine.main.MZmineLoggingConfiguration --enable-preview -Djpackage.app-path=/cluster/home/dning/mzmine/bin/mzmine
...
...
...
2024-08-08 15:57:26 FINEST io.github.mzmine.modules.io.import_rawdata_thermo_raw.ThermoRawImportTask unzipThermoRawFileParser Finished unpacking ThermoRawFileParser to folder /cluster/home/dning/mzmine/tmp/mzmine_thermo_raw_parser14545063827010551928
2024-08-08 15:57:26 SEVERE io.github.mzmine.modules.batchmode.BatchModeModule runBatch Error while running batch. null
java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.github.mzmine.taskcontrol.utils.TaskUtils.waitForTasksToFinish(TaskUtils.java:83)
	at io.github.mzmine.modules.batchmode.BatchTask.runTasksIndividually(BatchTask.java:421)
	at io.github.mzmine.modules.batchmode.BatchTask.processQueueStep(BatchTask.java:376)
	at io.github.mzmine.modules.batchmode.BatchTask.run(BatchTask.java:227)
	at io.github.mzmine.modules.batchmode.BatchModeModule.runBatch(BatchModeModule.java:137)
	at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:330)
#*******************************************************************
My mzbatch file was exported from Windows mzmine4.2.0 and the relevant file address directory was modified. I would like to consult the team. Is the problem encountered because the mzbatch file required by Linux is incompatible with the Windows version? Or perhaps it's due to reasons related to Java

Thanks

**Comment by Kirsteen426** [comment]
I have similar issues, but no clues whats going on. Anybody knows?

**Comment by ansgarkorf** [comment]
Can you try creating the batch file with a linux system?

**Comment by ashin947** [comment]
I don't know how to create it on a Linux system, I thought they were the same, so I only modified the addresses involved

**Comment by ansgarkorf** [comment]
YOu can create it on any linux based OS using our Linux version. Also consider the following, the second point, reducing the number of threads may help:

    You can set/limit used memory here: https://mzmine.github.io/mzmine_documentation/performance.html#maximum-memory
    The threads parameter in mzmine only limits the concurrent tasks, not the number of cpu cores used. you can use this parameter: -XX:ActiveProcessorCount=<count> to limit the cpu usage on a server. Add it where the previous option sets the memory
    General CLI usage follow this guide: https://mzmine.github.io/mzmine_documentation/commandline_tool.html (a valid user must be available)
    CLI arguments are listed here: https://mzmine.github.io/mzmine_documentation/commandline_tool.html#argument-table

**Comment by ashin947** [comment]
The Linux I use only has command-line mode and cannot open window mode. I am not familiar with how to create batch files. Can you provide me with a reference batch file so that I can make modifications.

**Comment by ashin947** [comment]
I think I've found the problem. It seems that the Linux version of mzmine only supports input files in *. mzML format, not *. raw
