### ISSUE TITLE
Spectral networking error

### ISSUE THREAD

**Issue by SteffenHeu** [mzmine/mzmine#2043]
If "Only best MS2 scan" is deactivated
![grafik](https://github.com/user-attachments/assets/3cdee360-ec32-490a-8a55-67cfb1b344bb)

```
2024-08-21 16:29:20 FINEST io.github.mzmine.main.MZmineCore setupAndRunModule Starting module Spectral / Molecular Networking with parameters Feature lists: Aligned feature list peak gaps dup gr, m/z tolerance (MS2): 0.001 m/z or 15.0 ppm, Only best MS2 scan: false, Max precursor m/z delta: true, Minimum matched signals: 6, Min cosine similarity: 0.7, Check MS2 neutral loss similarity: false, Signal filters: Remove residual precursor m/z: true, Crop to top N signals: 250, Signal threshold (intensity filter): 50, Intensity filter at >N signals: 0.98
2024-08-21 16:29:20 FINEST io.github.mzmine.main.MZmineCore runMZmineModule Module Spectral / Molecular Networking called at 2024-08-21T14:29:20.127119200Z
2024-08-21 16:29:20 INFO   io.github.mzmine.taskcontrol.impl.WrappedTask run Starting processing of task Check similarity of MSMS scans (mass lists)
2024-08-21 16:29:20 INFO   io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask checkAllFeatures Checking MS2 similarity on 189 rows
2024-08-21 16:29:20 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Unhandled exception java.lang.NullPointerException: Cannot invoke "io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask$FilteredRowData.data()" because the return value of "java.util.Map.get(Object)" is null while processing task Check similarity of MSMS scans (mass lists)
java.lang.NullPointerException: Cannot invoke "io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask$FilteredRowData.data()" because the return value of "java.util.Map.get(Object)" is null
    at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.checkR2RAllFeaturesMs2Similarity(SpectralNetworkingTask.java:588)
    at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.lambda$checkAllFeatures$7(SpectralNetworkingTask.java:565)
    at java.base/java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:246)
    at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.lambda$checkAllFeatures$6(SpectralNetworkingTask.java:561)
    at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:465)
    at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
    at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
    at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
    at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
    at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
    at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
    at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
    at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:676)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:264)
    at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:498)
    at java.base/java.util.stream.LongPipeline.sum(LongPipeline.java:456)
    at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.checkAllFeatures(SpectralNetworkingTask.java:570)
    at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.run(SpectralNetworkingTask.java:367)
    at io.github.mzmine.taskcontrol.impl.WrappedTask.run(WrappedTask.java:166)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by robinschmid** [comment]
Good catch. Will need to check what the issue is here maybe also problem with the hashmap key. 

Also this option should be renamed and then with a combobox to properly show the two options that are now only named for one case by checkbox.

**Comment by Kirsteen426** [comment]
> If "Only best MS2 scan" is deactivated ![grafik](https://private-user-images.githubusercontent.com/37407705/359955609-3cdee360-ec32-490a-8a55-67cfb1b344bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjYzNTcsIm5iZiI6MTcyNjA2NjA1NywicGF0aCI6Ii8zNzQwNzcwNS8zNTk5NTU2MDktM2NkZWUzNjAtZWMzMi00OTBhLThhNTUtNjdjZmIxYjM0NGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE0NDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OGZkNjE0YWNhZTIwNmYyMjIwZmFhOWY1YzQ1OTYwNzRlNTJlMjA1ZGQ4MWY0MGUyYmZmZDBjMmY1YTg2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7TU9csL-RqsAxNHFezIKqH8n4VHXxhLM2nbXcl8yLH0)
> 
> ```
> 2024-08-21 16:29:20 FINEST io.github.mzmine.main.MZmineCore setupAndRunModule Starting module Spectral / Molecular Networking with parameters Feature lists: Aligned feature list peak gaps dup gr, m/z tolerance (MS2): 0.001 m/z or 15.0 ppm, Only best MS2 scan: false, Max precursor m/z delta: true, Minimum matched signals: 6, Min cosine similarity: 0.7, Check MS2 neutral loss similarity: false, Signal filters: Remove residual precursor m/z: true, Crop to top N signals: 250, Signal threshold (intensity filter): 50, Intensity filter at >N signals: 0.98
> 2024-08-21 16:29:20 FINEST io.github.mzmine.main.MZmineCore runMZmineModule Module Spectral / Molecular Networking called at 2024-08-21T14:29:20.127119200Z
> 2024-08-21 16:29:20 INFO   io.github.mzmine.taskcontrol.impl.WrappedTask run Starting processing of task Check similarity of MSMS scans (mass lists)
> 2024-08-21 16:29:20 INFO   io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask checkAllFeatures Checking MS2 similarity on 189 rows
> 2024-08-21 16:29:20 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Unhandled exception java.lang.NullPointerException: Cannot invoke "io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask$FilteredRowData.data()" because the return value of "java.util.Map.get(Object)" is null while processing task Check similarity of MSMS scans (mass lists)
> java.lang.NullPointerException: Cannot invoke "io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask$FilteredRowData.data()" because the return value of "java.util.Map.get(Object)" is null
>     at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.checkR2RAllFeaturesMs2Similarity(SpectralNetworkingTask.java:588)
>     at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.lambda$checkAllFeatures$7(SpectralNetworkingTask.java:565)
>     at java.base/java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:246)
>     at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.lambda$checkAllFeatures$6(SpectralNetworkingTask.java:561)
>     at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:465)
>     at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
>     at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
>     at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
>     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
>     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
>     at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
>     at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
>     at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
>     at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
>     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
>     at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:676)
>     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
>     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:264)
>     at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:498)
>     at java.base/java.util.stream.LongPipeline.sum(LongPipeline.java:456)
>     at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.checkAllFeatures(SpectralNetworkingTask.java:570)
>     at io.github.mzmine.modules.dataprocessing.group_spectral_networking.SpectralNetworkingTask.run(SpectralNetworkingTask.java:367)
>     at io.github.mzmine.taskcontrol.impl.WrappedTask.run(WrappedTask.java:166)
>     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
>     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
>     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
>     at java.base/java.lang.Thread.run(Thread.java:1570)
> ```

Hi, I came cross the MS2 spectral matching or searching problems, for instance, L-arginine has good MS2 spectral by QE-plus positive mode acquisition.  Fragments like m/z 158.0925, 130.0964 ,116.0706 ,70.0652 etc. were well generated by HCD collision of L-Arginine. However, mzmine did not recognize L-arginine ms2 or has no match to Arginine or no match with m/z 175.1190 (I can see it in the feature list). We set quite large m/z tolerance range. Can you kindly work out the possible reasons? Thanks.
![arginine](https://github.com/user-attachments/assets/92c2490d-be03-4c4f-9bc8-67e5303a4c96)
![arginine settings](https://github.com/user-attachments/assets/7597c57a-f64a-44f9-8f1c-4f0591bf6b58)
![arginine ref](https://github.com/user-attachments/assets/1fd7e61f-5a5e-46b1-9612-445affe9a1ef)

**Comment by robinschmid** [comment]
Please open a separate issue for this. This is unrelated to the original issue. 
Use the wizard to setup a batch and see that you find your precursor ion in the feature table and that it has MS2 spectra.
