### ISSUE TITLE
Problem of running new release in the HPC

### ISSUE THREAD

**Issue by cemilcansaylan** [mzmine/mzmine#2254]
### Basic information

* My operating system and version: Linux 5.15.0-105-generic x86_64
* My mzmine version: 4.4.0

### What happened
Previously I was working on 4.3.0 release in our HPC cluster. It was working nicely, but I also had a memory problem when working on 225 Lipidomics DDA samples, which I believe is similar to [Issue #2023](https://github.com/mzmine/mzmine/issues/2023). However, when I tried to use the new version, 4.4.0, I had the error below. When I used v4.3.0 with the same parameters and script, I did not have any problem. Moreover, I used the login node terminal (directly I run in the terminal) to execute the script for v4.4.0, and I did not get an error, it worked. Do I need to define something in the slurm script? 

the line for mzmine run in the slurm script;
`
$mzmine_path/bin/mzmine --threads $SLURM_CPUS_PER_TASK --user $mzmine_path/usr/cemilcansaylan.mzuser --batch ./pos_mode_3.mzbatch --memory "none"
`
It returns these for v4.4.0:
```
2024-11-22 12:47:08 FINEST io.github.mzmine.main.MZmineCore main Working directory is /cmnfs/home/c.saylan/Projects/Lipidomics/Arabidopsis_HS_IA/1_lipididentification/mzmine/test
2024-11-22 12:47:08 FINEST io.github.mzmine.main.MZmineCore main Default temporary directory is /tmp
2024-11-22 12:47:08 FINE   io.github.mzmine.main.TmpFileCleanup run Checking for old temporary files...
2024-11-22 12:47:09 INFO   io.mzio.users.user.CurrentUserService setUser User changed to cemilcansaylan
2024-11-22 12:47:09 INFO   io.mzio.mzmine.startup.MZmineCoreArgumentParser parse Batch file set by command line: ./pos_mode_3.mzbatch
2024-11-22 12:47:09 WARNING io.github.mzmine.main.MZmineCore main Cannot read configuration /cmnfs/home/c.saylan/.mzmine/.mzconfig
2024-11-22 12:47:09 FINEST io.github.mzmine.taskcontrol.TaskControllerImpl <init> Starting task controller thread
2024-11-22 12:47:09 SEVERE io.github.mzmine.main.MZmineCore main Error during mzmine start up
java.lang.NullPointerException: Cannot invoke "java.io.Console.isTerminal()" because the return value of "java.lang.System.console()" is null
	at io.github.mzmine.gui.DesktopService.hasTerminalInput(DesktopService.java:58)
	at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:292)
```
It returns these for v4.3.0:
```
024-11-22 12:51:57 FINEST io.github.mzmine.main.MZmineCore main Working directory is /cmnfs/home/c.saylan/Projects/Lipidomics/Arabidopsis_HS_IA/1_lipididentification/mzmine/test
2024-11-22 12:51:57 FINEST io.github.mzmine.main.MZmineCore main Default temporary directory is /tmp
2024-11-22 12:51:57 FINE   io.github.mzmine.main.TmpFileCleanup run Checking for old temporary files...
2024-11-22 12:51:57 INFO   io.mzio.users.user.CurrentUserService setUser User changed to cemilcansaylan
2024-11-22 12:51:57 INFO   io.mzio.mzmine.startup.MZmineCoreArgumentParser parse Batch file set by command line: ./pos_mode_3.mzbatch
2024-11-22 12:51:57 WARNING io.github.mzmine.main.MZmineCore main Cannot read configuration /cmnfs/home/c.saylan/.mzmine/.mzconfig
2024-11-22 12:51:57 FINEST io.github.mzmine.taskcontrol.TaskControllerImpl <init> Starting task controller thread
2024-11-22 12:51:57 INFO   io.github.mzmine.modules.batchmode.BatchModeModule runBatch Running batch from file ./pos_mode_3.mzbatch
2024-11-22 12:51:57 INFO   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml The batch file was created with the same version of MZmine4.3.0 (this version is 4.3.0).
2024-11-22 12:51:57 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.filter_rowsfilter.RowsFilterModule
2024-11-22 12:51:57 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.io.import_rawdata_all.AllSpectralDataImportModule
2024-11-22 12:51:57 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.io.import_rawdata_all.AllSpectralDataImportModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_massdetection.factor_of_lowest.FactorOfLowestMassDetector
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_massdetection.auto.AutoMassDetector
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_massdetection.centroid.CentroidMassDetector
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_massdetection.exactmass.ExactMassDetector
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_massdetection.localmaxima.LocalMaxMassDetector
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_massdetection.recursive.RecursiveMassDetector
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_massdetection.wavelet.WaveletMassDetector
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.featdet_adapchromatogrambuilder.ModularADAPChromatogramBuilderModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_adapchromatogrambuilder.ModularADAPChromatogramBuilderModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.featdet_smoothing.SmoothingModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_smoothing.SmoothingModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_smoothing.loess.LoessSmoothing
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_smoothing.savitzkygolay.SavitzkyGolaySmoothing
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.featdet_chromatogramdeconvolution.minimumsearch.MinimumSearchFeatureResolverModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.featdet_chromatogramdeconvolution.minimumsearch.MinimumSearchFeatureResolverModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.filter_isotopegrouper.IsotopeGrouperModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.filter_isotopegrouper.IsotopeGrouperModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.align_join.JoinAlignerModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.align_join.JoinAlignerModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.util.scans.similarity.impl.cosine.WeightedCosineSpectralSimilarity
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.util.scans.similarity.impl.composite.CompositeCosineSpectralSimilarity
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.filter_blanksubtraction.FeatureListBlankSubtractionModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.filter_blanksubtraction.FeatureListBlankSubtractionModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.filter_rowsfilter.RowsFilterModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.gapfill_peakfinder.multithreaded.MultiThreadPeakFinderModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.gapfill_peakfinder.multithreaded.MultiThreadPeakFinderModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.filter_duplicatefilter.DuplicateFilterModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.filter_duplicatefilter.DuplicateFilterModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.group_metacorrelate.corrgrouping.CorrelateGroupingModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.group_metacorrelate.corrgrouping.CorrelateGroupingModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.id_spectral_library_match.SpectralLibrarySearchModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.id_spectral_library_match.SpectralLibrarySearchModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.dataprocessing.id_lipidid.annotation_modules.LipidAnnotationModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.dataprocessing.id_lipidid.annotation_modules.LipidAnnotationModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.io.export_features_csv_legacy.LegacyCSVExportModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.io.export_features_csv_legacy.LegacyCSVExportModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.io.export_compoundAnnotations_csv.CompoundAnnotationsCSVExportModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.io.export_compoundAnnotations_csv.CompoundAnnotationsCSVExportModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.io.export_features_gnps.fbmn.GnpsFbmnExportAndSubmitModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.io.export_features_gnps.fbmn.GnpsFbmnExportAndSubmitModule
2024-11-22 12:51:58 FINE   io.github.mzmine.modules.batchmode.BatchQueue loadFromXml Loading batch step: io.github.mzmine.modules.io.export_features_metaboanalyst.MetaboAnalystExportModule
2024-11-22 12:51:58 FINEST io.github.mzmine.main.MZmineCore getModuleInstance Creating an instance of the module io.github.mzmine.modules.io.export_features_metaboanalyst.MetaboAnalystExportModule
```
..... continues

**Comment by SteffenHeu** [comment]
Hi, 

thank you for the report. we will look into this.

**Comment by jsp333333** [comment]
My operating system and version: Windows x64
My mzmine version: 4.4.0

An LC-QTOF 9030 (Shimadzu) was employed and raw data files were transformed to mzML (centroid), previous versions of mzMine did work perfectly, but after downloading the latest version we cannot import the data the process is being canceled.  

Log file indicating the errors:

2024-11-26 17:04:36 WARNING io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask importStreamOrFile Error during mzML read: Out of bound access on segment MemorySegment{ heapBase: [D@95b07bd, address: 0x0, byteSize: 0 }; new offset = -8; new length = 8
java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ heapBase: [D@95b07bd, address: 0x0, byteSize: 0 }; new offset = -8; new length = 8
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.outOfBoundException(AbstractMemorySegmentImpl.java:434)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:415)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:70)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:124)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:448)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkBounds(AbstractMemorySegmentImpl.java:404)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkAccess(AbstractMemorySegmentImpl.java:364)
	at java.base/java.lang.invoke.VarHandleSegmentAsDoubles.checkAddress(VarHandleSegmentAsDoubles.java:88)
	at java.base/java.lang.invoke.VarHandleSegmentAsDoubles.get(VarHandleSegmentAsDoubles.java:114)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.getAtIndex(AbstractMemorySegmentImpl.java:935)
	at io.github.mzmine.datamodel.featuredata.IntensitySeries.getIntensity(IntensitySeries.java:93)
	at io.github.mzmine.datamodel.featuredata.FeatureDataUtils.recalculateIntensityTimeSeriesDependingTypes(FeatureDataUtils.java:288)
	at io.github.mzmine.datamodel.otherdetectors.OtherFeatureImpl.<init>(OtherFeatureImpl.java:45)
	at io.github.mzmine.modules.io.import_rawdata_mzml.ConversionUtils.convertOtherTraces(ConversionUtils.java:408)
	at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.importStreamOrFile(MSDKmzMLImportTask.java:225)
	at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.run(MSDKmzMLImportTask.java:163)
	at io.github.mzmine.taskcontrol.impl.WrappedTask.run(WrappedTask.java:169)
	at io.github.mzmine.taskcontrol.threadpools.ThreadPoolTask.lambda$trackProgressTask$3(ThreadPoolTask.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

2024-11-26 17:04:36 FINEST io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask parseMzMlInternal Parsing Complete
2024-11-26 17:04:36 INFO   io.github.mzmine.taskcontrol.impl.WrappedTask run Processing of task Importing raw data file: QC_Pos_02_006.mzML done, status CANCELED
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing data: Subtask had an error or was interrupted
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_Inc_Pos_02_009.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_Inc_Pos_03_010.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_Pos_01_005.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_FS_Pos_02_007.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_Pos_03_015.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_FS_Pos_01_006.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing QC_Inc_Pos_01_008.mzML, total / parsed is 7514 / 7514: Error parsing mzML: java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ heapBase: [D@95b07bd, address: 0x0, byteSize: 0 }; new offset = -8; new length = 8 (AbstractMemorySegmentImpl.java:434)
2024-11-26 17:04:36 WARNING io.github.mzmine.modules.batchmode.BatchTask run Subtask had an error or was interrupted
2024-11-26 17:04:36 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Batch step 2/19: Subtask had an error or was interrupted

**Comment by ansgarkorf** [comment]
@jsp333333 can you please open a new issue?

**Comment by SteffenHeu** [comment]
@cemilcansaylan Please try mzmine 4.4.3 https://github.com/mzmine/mzmine/releases/tag/v4.4.3, it should be fixed
