### ISSUE TITLE
GC-EI-MS molecular networking

### ISSUE THREAD

**Issue by collinsdoug** [mzmine/mzmine#2255]
### Basic information

* My operating system and version: Windows 10 Education
* My mzmine version: 4.4.0

### What happened
I was attempting to use the new Spectral/Molecular Networking tool developed for GC-EI-MS data. This is low resolution (single quad) data. There are about 30 injection/raw files in this project, all of which are aligned in this feature list. 

When running the Spectral/Molecular Networking tool on an aligned feature list, I get the following in the log file. It looks like it's running initially and then throws an exception part way through. Any ideas?

2024-11-22 15:23:18 INFO   io.github.mzmine.gui.mainwindow.MainMenuController runModule Menu item activated for module io.github.mzmine.modules.dataprocessing.group_spectral_networking.MainSpectralNetworkingModule
2024-11-22 15:23:18 INFO   io.github.mzmine.main.MZmineCore setupAndRunModule Setting parameters for module Spectral / Molecular Networking
2024-11-22 15:23:35 FINEST io.github.mzmine.main.MZmineCore setupAndRunModule Starting module Spectral / Molecular Networking with parameters Feature lists: Aligned feature list peak (1), Algorithm: Cosine similarity (GC-EI-MS)
2024-11-22 15:23:35 FINEST io.github.mzmine.main.MZmineCore runMZmineModule Module Spectral / Molecular Networking called at 2024-11-22T20:23:35.253262800Z
2024-11-22 15:23:35 INFO   io.github.mzmine.taskcontrol.impl.WrappedTask run Starting processing of task Check cosine similarity of pseudo MS2 scans (mass lists)
2024-11-22 15:23:35 INFO   io.github.mzmine.modules.dataprocessing.group_spectral_networking.cosine_no_precursor.NoPrecursorCosineSpectralNetworkingTask checkRowsBestMs2 Checking MS2 similarity on 35 rows
2024-11-22 15:23:35 INFO   io.github.mzmine.modules.dataprocessing.group_spectral_networking.cosine_no_precursor.NoPrecursorCosineSpectralNetworkingTask checkRowsBestMs2 Spectral networking: Performed 595 pairwise comparisons.
2024-11-22 15:23:35 INFO   io.github.mzmine.modules.dataprocessing.group_spectral_networking.cosine_no_precursor.NoPrecursorCosineSpectralNetworkingTask process GC-EI-MS cosine similarity check on rows done. MS cosine similarity edges=196
2024-11-22 15:23:35 FINE   io.github.mzmine.datamodel.features.correlation.R2RNetworkingMaps addAllRowsRelationships Added n=196 feature row relationships (network edges) of type: MS2 (modified) cosine
2024-11-22 15:23:35 FINE   io.github.mzmine.datamodel.features.correlation.R2RNetworkingMaps addAllRowsRelationships Added n=197 feature row relationships (network edges) of type: MS2 (modified) cosine
2024-11-22 15:23:35 INFO   io.github.mzmine.modules.visualization.networking.visual.FeatureNetworkGenerator createNewGraph Adding all annotations to a network
2024-11-22 15:23:35 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Unhandled exception java.lang.NullPointerException: Cannot read the array length because the return value of "io.github.mzmine.util.scans.similarity.SpectralSimilarity.getAlignedDataPoints()" is null while processing task Check cosine similarity of pseudo MS2 scans (mass lists)
java.lang.NullPointerException: Cannot read the array length because the return value of "io.github.mzmine.util.scans.similarity.SpectralSimilarity.getAlignedDataPoints()" is null
	at io.github.mzmine.modules.visualization.networking.visual.enums.NodeAtt.lambda$getValue$1(NodeAtt.java:187)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1686)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:144)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:574)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:662)
	at io.github.mzmine.modules.visualization.networking.visual.enums.NodeAtt.getValue(NodeAtt.java:187)
	at io.github.mzmine.modules.visualization.networking.visual.enums.NodeAtt.getFormattedValue(NodeAtt.java:265)
	at io.github.mzmine.modules.visualization.networking.visual.FeatureNetworkGenerator.getRowNode(FeatureNetworkGenerator.java:561)
	at io.github.mzmine.modules.visualization.networking.visual.FeatureNetworkGenerator.getRowNode(FeatureNetworkGenerator.java:544)
	at io.github.mzmine.modules.visualization.networking.visual.FeatureNetworkGenerator.addMS2SimEdges(FeatureNetworkGenerator.java:321)
	at io.github.mzmine.modules.visualization.networking.visual.FeatureNetworkGenerator.addRelationshipEdges(FeatureNetworkGenerator.java:314)
	at io.github.mzmine.modules.visualization.networking.visual.FeatureNetworkGenerator.createNewGraph(FeatureNetworkGenerator.java:124)
	at io.github.mzmine.modules.visualization.networking.visual.FeatureNetworkGenerator.createNewGraph(FeatureNetworkGenerator.java:97)
	at io.github.mzmine.modules.dataprocessing.group_spectral_networking.modified_cosine.ModifiedCosineSpectralNetworkingTask.addNetworkStatisticsToRows(ModifiedCosineSpectralNetworkingTask.java:411)
	at io.github.mzmine.modules.dataprocessing.group_spectral_networking.cosine_no_precursor.NoPrecursorCosineSpectralNetworkingTask.process(NoPrecursorCosineSpectralNetworkingTask.java:126)
	at io.github.mzmine.taskcontrol.AbstractSimpleToolTask.run(AbstractSimpleToolTask.java:78)
	at io.github.mzmine.taskcontrol.AbstractSimpleTask.run(AbstractSimpleTask.java:67)
	at io.github.mzmine.taskcontrol.impl.WrappedTask.run(WrappedTask.java:169)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

Here is the setup for the Molecular Networking:
![MolecNetwork_setup](https://github.com/user-attachments/assets/2a1a21a6-3c3b-476a-889d-e56dfa3a66a6)

Full Log file attached:
[MolecNetwork_Exception_22Nov2024_mzmine_0_0.log](https://github.com/user-attachments/files/17876142/MolecNetwork_Exception_22Nov2024_mzmine_0_0.log)

**Comment by ansgarkorf** [comment]
Hi,
Please also share your batch file. Did you use the mzwizard?

**Comment by ansgarkorf** [comment]
Please have a look at this video 28:15 min https://www.youtube.com/watch?v=cGA5WIKcMpM
There you can see how to use the GC/EI spectral deconvolution visualization.
Please also checkout the following documentation:
https://mzmine.github.io/mzmine_documentation/module_docs/group_spectral_net/molecular_networking.html
https://mzmine.github.io/mzmine_documentation/module_docs/featdet_spectraldeconvolutiongc/spectraldeconvolutiongc.html

I will look into the empty GNPS export.

**Comment by ansgarkorf** [comment]
Glad the networking now works. We will need to look into your NIST issue. To be honest, the NIST implementation is a bit outdated. We have a new NIST implementation on the roadmap for 2025.
