### ISSUE TITLE
mzTab-M Import Show Feature list shows Unspecified Error

### ISSUE THREAD

**Issue by nilshoffmann** [mzmine/mzmine#803]
### Basic information

* My operating system: Ubuntu 21.04
* My MZmine version: Development / Master, 3.1.12-beta, 
* Currently working off of my branch here, which is synced with master: https://github.com/nilshoffmann/mzmine3/tree/mzTab-support

### What happened

* Import of feature list without raw files via Import, mzTab-M module (File DataS-1_mztab.txt from this supplement: https://pubs.acs.org/doi/suppl/10.1021/acs.analchem.0c03016/suppl_file/ac0c03016_si_002.zip).
* Import raw files too was disabled. 
* Open feature list tab, double click on Aligned feature lists, DataS-1.mzTab to open the feature table
* Feature table opens, correctly displays retention time 
* Console logs multiple NullPointerExceptions, one for each row of the table.
* UI displays modal error dialog, once for every row :-)
* Please see the screenshot below for the open feature table view and the error dialog.
* I do not have a project file available, since the (few hundred) modals block the UI.

Stack Trace:
```
INFO: It seems you are running MZmine version 3.1.12-beta, which is newer than the latest official release 3.1.0-beta
Jul 20, 2022 8:53:50 AM io.github.mzmine.gui.mainwindow.MainMenuController runModule
INFO: Menu item activated for module io.github.mzmine.modules.io.import_features_mztabm.MZTabmImportModule
Jul 20, 2022 8:53:50 AM io.github.mzmine.gui.mainwindow.MainMenuController runModule
INFO: Setting parameters for module Import mzTab-m file
Jul 20, 2022 8:53:55 AM io.github.mzmine.taskcontrol.impl.WorkerThread run
INFO: Starting processing of task Loading feature list from mzTab-m file /home/nilshoffmann/Projects/github.com/lifs-tools/lipidcompass-submissions/submissions/LCE00000005/data/ac0c03016_si_002/DataS-1_mztab.mzTab
No structural or logical errors in file:/home/nilshoffmann/Projects/github.com/lifs-tools/lipidcompass-submissions/submissions/LCE00000005/data/ac0c03016_si_002/DataS-1_mztab.mzTab file!
Jul 20, 2022 8:53:56 AM io.github.mzmine.taskcontrol.impl.WorkerThread run
INFO: Processing of task Loading feature list from mzTab-m file /home/nilshoffmann/Projects/github.com/lifs-tools/lipidcompass-submissions/submissions/LCE00000005/data/ac0c03016_si_002/DataS-1_mztab.mzTab done, status FINISHED
Jul 20, 2022 8:54:19 AM io.github.mzmine.taskcontrol.impl.WorkerThread run
INFO: Starting processing of task Creating a graphical column for col: Shapes in row: 1
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.github.mzmine.datamodel.features.types.tasks.FeaturesGraphicalNodeTask.run(FeaturesGraphicalNodeTask.java:64)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
Caused by: java.lang.NullPointerException: Cannot invoke "io.github.mzmine.datamodel.Scan.getRetentionTime()" because the return value of "java.util.List.get(int)" is null
	at io.github.mzmine.datamodel.featuredata.impl.SimpleIonTimeSeries.getRetentionTime(SimpleIonTimeSeries.java:175)
	at io.github.mzmine.gui.chartbasics.simplechart.providers.impl.series.IonTimeSeriesToXYProvider.getDomainValue(IonTimeSeriesToXYProvider.java:98)
	at io.github.mzmine.gui.chartbasics.simplechart.datasets.ColoredXYDataset.run(ColoredXYDataset.java:307)
	at io.github.mzmine.gui.chartbasics.simplechart.datasets.ColoredXYDataset.handleRunOption(ColoredXYDataset.java:131)
	at io.github.mzmine.gui.chartbasics.simplechart.datasets.ColoredXYDataset.<init>(ColoredXYDataset.java:107)
	at io.github.mzmine.gui.chartbasics.simplechart.datasets.ColoredXYDataset.<init>(ColoredXYDataset.java:117)
	at io.github.mzmine.datamodel.features.types.graphicalnodes.FeatureShapeChart.<init>(FeatureShapeChart.java:65)
	... 7 more
```
![Bildschirmfoto vom 2022-07-20 08-56-23](https://user-images.githubusercontent.com/3309580/179918061-5207efe2-0582-4cdf-aa26-33116857b736.png)

**Comment by SteffenHeu** [comment]
The data model (currently) does not support feature tables without the coresponding raw data files. Is this something we have to support? @nilshoffmann @robinschmid @tomas-pluskal

**Comment by nilshoffmann** [comment]
I would prefer to have a fallback since at least I do not always have access to the raw data files. Since we "usually" also supply the (aligned) retention time of features, being able to plot would make sense in my opinion. Also, multiple feature rows could be linked via the summary level  entries to generate pseudospectra.

**Comment by nilshoffmann** [comment]
The main problem however at the moment is that the UI becomes totally unusable due to the potentially hundreds of modal error messages.
